using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace CodeSugar.Numerics
{
    [Generator]
    public sealed class InjectTemplateExtensions : CodeInjectorGenerator
    {
        protected override void InjectSources(SourceProductionContext context)
        {
            var hasTensors = this.NugetPackages.ContainsKey("System.Numerics.Tensors");
            var hasImageSharp = this.NugetPackages.ContainsKey("SixLabors.ImageSharp");
            var hasMagicScaler = this.NugetPackages.ContainsKey("PhotoSauce.MagicScaler");
            var hasSkiaSharp = this.NugetPackages.ContainsKey("SkiaSharp");

            ProcessTemplates(context,"Core", n => n.Contains(".Templates.Core."));

            // imaging

            if (hasImageSharp) ProcessTemplates(context, "ImageSharp", n => n.Contains(".Templates.ImageSharp."));
            if (hasMagicScaler) ProcessTemplates(context, "MagicScaler", n => n.Contains(".Templates.MagicScaler."));
            if (hasSkiaSharp) ProcessTemplates(context, "SkiaSharp", n => n.Contains(".Templates.SkiaSharp."));

            if (hasTensors) // tensors
            {
                ProcessTemplates(context, "Tensors", n => n.Contains(".Templates.Tensors."));
                ProcessTemplates(context, "Intrinsics", n => n.Contains(".Templates.Intrinsics."));
            }            

            if (hasTensors) // imaging interop with tensors
            {
                if (hasImageSharp) ProcessTemplates(context, "ImageSharpTensors", n => n.Contains(".Templates.ImageSharpTensors."));
                if (hasMagicScaler) ProcessTemplates(context, "MagicScalerTensors", n => n.Contains(".Templates.MagicScalerTensors."));
                if (hasSkiaSharp) ProcessTemplates(context, "SkiaSharpTensors", n => n.Contains(".Templates.SkiaSharpTensors."));
            }            
        }

        private int _TemplateIndex = 0;

        private void ProcessTemplates(SourceProductionContext context, string name, Predicate<string> nameChecker)
        {
            var selfAssembly = typeof(InjectTemplateExtensions).Assembly;

            foreach (var resName in selfAssembly.GetManifestResourceNames())
            {
                if (!resName.EndsWith(".cs")) continue;

                if (!nameChecker(resName)) continue;


                using (var s = selfAssembly.GetManifestResourceStream(resName))
                {
                    using (var t = new System.IO.StreamReader(s))
                    {
                        var code = t.ReadToEnd();
                        code = ProcessTemplate(code, this.RootNameSpace, this.NugetPackages);
                        context.AddSource($"CodeSugar.{name}{_TemplateIndex}.g.cs", code);
                        _TemplateIndex++;
                    }
                }
            }
        }

        private static string ProcessTemplate(string templateCode, string nameSpace, IReadOnlyDictionary<string, string> nugets)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();

            foreach (var n in nugets)
            {
                if (n.Key == "System.Numerics.Tensors" || n.Key == "SixLabors.ImageSharp" || n.Key == "PhotoSauce.MagicScaler" || n.Key == "SkiaSharp")
                {
                    var declaration = "#define __REFERENCES_" + n.Key.Replace(".", "").ToUpper();
                    sb.AppendLine(declaration);
                }
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", nameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", nameSpace);
            
            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }
}
