using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace CodeSugar
{
    [Generator]
    public sealed class InjectTemplateExtensions : CodeInjectorGenerator
    {
        protected override void InjectSources(SourceProductionContext context)
        {
            ProcessTemplates(context,"Progress", n => n.Contains(".Progress."));            
        }

        private int _TemplateIndex = 0;

        private void ProcessTemplates(SourceProductionContext context, string name, Predicate<string> nameChecker)
        {
            var selfAssembly = typeof(InjectTemplateExtensions).Assembly;

            foreach (var resName in selfAssembly.GetManifestResourceNames())
            {
                if (!resName.EndsWith(".cs")) continue;

                if (!nameChecker(resName)) continue;


                using (var s = selfAssembly.GetManifestResourceStream(resName))
                {
                    using (var t = new System.IO.StreamReader(s))
                    {
                        var code = t.ReadToEnd();
                        code = ProcessTemplate(code, this.RootNameSpace, this.NugetPackages);
                        context.AddSource($"CodeSugar.{name}{_TemplateIndex}.g.cs", code);
                        _TemplateIndex++;
                    }
                }
            }
        }

        private static string ProcessTemplate(string templateCode, string nameSpace, IReadOnlyDictionary<string, string> nugets)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();

            foreach (var n in nugets)
            {
                if (n.Key == "System.Numerics.Tensors" || n.Key == "NCalc")
                {
                    var declaration = "#define __REFERENCES_" + n.Key.Replace(".", "").ToUpper();
                    sb.AppendLine(declaration);
                }
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", nameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", nameSpace);
            
            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }
}
