// <auto-generated />
// Copyright (c) CodeSugar 2024 Vicente Penades

using System;
using System.Numerics;
using System.Numerics.Tensors;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

using System.Runtime.Intrinsics;

#nullable disable

using __XYZ = System.Numerics.Vector3;
using __XYZW = System.Numerics.Vector4;

#if CODESUGAR_USECODESUGARNAMESPACE
namespace CodeSugar
#elif CODESUGAR_USESYSTEMNAMESPACE
namespace System.Numerics.Tensors
#else
namespace $rootnamespace$
#endif
{
    partial class CodeSugarForTensors
    {

    
        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGB>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _StepSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<byte> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<byte, _RGBA>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector3 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGB>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<byte> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<byte, _RGBA>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaStep(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _StepSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


        /// <summary>
        /// Draws the bitmap represented by srcBitmap into dstBitmap using the given transform
        /// </summary>
        /// <param name="dstBitmap">The render target bitmap</param>
        /// <param name="srcTransform">The transform of the source bitmap</param>
        /// <param name="srcBitmap">The source bitmap</param>
        public static void DrawRgbaPixelsOverRgbaBilinear(this System.Numerics.Tensors.TensorSpan<float> dstBitmap, System.Numerics.Matrix3x2 srcTransform, System.Numerics.Tensors.ReadOnlyTensorSpan<float> srcBitmap)
        {
            var srcSampler = new _BilinearSampler<float, _RGBAf>(srcBitmap);
            var srcXform = new _SamplerTransform(srcTransform);
            var dstRendTgt = new _TensorSpanBitmapHWC<float, _RGBAf>(dstBitmap);

            for(int y=0; y < dstRendTgt.Height; ++y)
            {
                var dstRow = dstRendTgt.GetRowSpan(y);
                for(int x=0; x < dstRow.Length; ++x)
                {
                    if (srcSampler.TryGetSample(srcXform.Transform(x, y), out Vector4 sample))
                    {
                        dstRow[x].Assign(sample);
                    }
                }
            }
        }


    }
}
