using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Text;
using System.Xml.Linq;

using Microsoft.CodeAnalysis.CSharp;

namespace CodeSugar
{
    class TemplateCodeProcessor
    {
        public TemplateCodeProcessor(CodeGenerationContext context)
        {
            Context = context;
        }

        public CodeGenerationContext Context { get; }        

        private readonly HashSet<string> _RelevantNugets = new HashSet<string>();        

        public void UsesNuget(string id) { _RelevantNugets.Add(id); }

        public string ProcessTemplate(string templateCode)
        {
            if (!Context.LangSupportsNullable) templateCode = templateCode.Replace("#nullable disable", string.Empty);

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();

            sb.AppendLine($"// LangVersion: {Context.LangVersion}");
            sb.AppendLine();

            foreach(var lv in Enum.GetValues(typeof(LanguageVersion)).OfType<LanguageVersion>())
            {
                if (lv == LanguageVersion.Default) continue;
                if (lv == LanguageVersion.LatestMajor) break;

                var name = Enum.GetName(typeof(LanguageVersion), lv).ToUpper();
                sb.AppendLine($"#define __LANGVERSION_{name}_OR_GREATER");

                if (lv == Context.LangVersion) break;
            }

            foreach (var k in _RelevantNugets)
            {
                if (!Context.NugetPackages.ContainsKey(k)) continue;

                var declaration = "#define __REFERENCES_" + k.Replace(".", "").ToUpper();
                sb.AppendLine(declaration);
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", Context.RootNameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", Context.RootNameSpace);

            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }




}