using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Text;
using System.Xml.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace CodeSugar
{
    class TemplateCodeProcessor
    {
        public string RootNameSpace { get; set; } = "CodeSugar";

        public IReadOnlyDictionary<string, string> AllNugets { get; set; } = new Dictionary<string, string>();

        private readonly HashSet<string> _RelevantNugets = new HashSet<string>();

        public void UsesNuget(string id) { _RelevantNugets.Add(id); }

        public string ProcessTemplate(string templateCode)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();

            foreach (var k in _RelevantNugets)
            {
                if (!AllNugets.ContainsKey(k)) continue;

                var declaration = "#define __REFERENCES_" + k.Replace(".", "").ToUpper();
                sb.AppendLine(declaration);
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", RootNameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", RootNameSpace);

            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }




}