using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Text;
using System.Xml.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace CodeSugar
{
    class TemplateCodeProcessor
    {
        public TemplateCodeProcessor(string rootNameSpace, LanguageVersion langVersion, IReadOnlyDictionary<string, string> allNugets)
        {
            this.RootNameSpace = rootNameSpace;
            this.LangVersion = langVersion.MapSpecifiedToEffectiveVersion();
            this.AllNugets = allNugets;
        }

        public string RootNameSpace { get; private set; } = "CodeSugar";
        public LanguageVersion LangVersion { get; private set; }
        protected bool LangSupportsNullable => LangVersion >= LanguageVersion.CSharp8;
        protected bool LangSupportsGenericAttrs => LangVersion >= LanguageVersion.CSharp11;

        public IReadOnlyDictionary<string, string> AllNugets { get; private set; } = new Dictionary<string, string>();

        private readonly HashSet<string> _RelevantNugets = new HashSet<string>();

        

        public void UsesNuget(string id) { _RelevantNugets.Add(id); }

        public string ProcessTemplate(string templateCode)
        {
            if (!LangSupportsNullable) templateCode = templateCode.Replace("#nullable disable", $"// {LangVersion}");

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();
            sb.AppendLine($"// LangVersion: {LangVersion}");
            sb.AppendLine();

            foreach (var k in _RelevantNugets)
            {
                if (!AllNugets.ContainsKey(k)) continue;

                var declaration = "#define __REFERENCES_" + k.Replace(".", "").ToUpper();
                sb.AppendLine(declaration);
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", RootNameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", RootNameSpace);

            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }




}