using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace CodeSugar.IO
{
    [Generator]
    public sealed class InjectTemplateExtensions : CodeInjectorGenerator
    {
        protected override void InjectSources(SourceProductionContext context)
        {
            var hasAbstractions = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Abstractions");
            var hasPhysical = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Physical");
            var hasEmbedded = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Embedded");
            var hasComposite = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Composite");
            var hasBigMemoryStream = this.NugetPackages.ContainsKey("Microsoft.IO.RecyclableMemoryStream");
            var hasSharpCompress = this.NugetPackages.ContainsKey("SharpCompress");            

            ProcessTemplates(context,"SystemIO", n => n.Contains(".Templates.SystemIO."));

            if (hasAbstractions) ProcessTemplates(context,"FileProviders", n => n.Contains(".Templates.FileProviders."));
            if (hasSharpCompress) ProcessTemplates(context, "SharpCompress", n => n.Contains(".Templates.SharpCompress."));
        }

        private int _TemplateIndex = 0;

        private void ProcessTemplates(SourceProductionContext context, string name, Predicate<string> nameChecker)
        {
            var selfAssembly = typeof(InjectTemplateExtensions).Assembly;

            foreach (var resName in selfAssembly.GetManifestResourceNames())
            {
                if (!resName.EndsWith(".cs")) continue;

                if (!nameChecker(resName)) continue;


                using (var s = selfAssembly.GetManifestResourceStream(resName))
                {
                    using (var t = new System.IO.StreamReader(s))
                    {
                        var code = t.ReadToEnd();
                        code = ProcessTemplate(code, this.RootNameSpace, this.NugetPackages);
                        context.AddSource($"CodeSugar.{name}{_TemplateIndex}.g.cs", code);
                        _TemplateIndex++;
                    }
                }
            }
        }

        private static string ProcessTemplate(string templateCode, string nameSpace, IReadOnlyDictionary<string, string> nugets)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"// Copyright (c) CodeSugar {DateTime.Today.Year} Vicente Penades");
            sb.AppendLine();

            foreach (var n in nugets)
            {
                if (n.Key.StartsWith("Microsoft.Extensions") || n.Key == "SharpCompress" || n.Key.EndsWith("RecyclableMemoryStream"))
                {
                    var declaration = "#define __REFERENCES_" + n.Key.Replace(".", "").ToUpper();
                    sb.AppendLine(declaration);
                }
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", nameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", nameSpace);
            
            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }
}
