using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace CodeSugar.FileProviders.SourceGenerators
{
    [Generator]
    public sealed class InjectTemplateExtensions : CodeInjectorGenerator
    {
        protected override void InjectSources(SourceProductionContext context)
        {
            var hasAbstractions = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Abstractions");
            var hasPhysical = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Physical");
            var hasEmbedded = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Embedded");
            var hasComposite = this.NugetPackages.ContainsKey("Microsoft.Extensions.FileProviders.Composite");
            var hasSharpCompress = this.NugetPackages.ContainsKey("SharpCompress");

            if (!hasAbstractions) return; // nothing to do

            var selfAssembly = typeof(InjectTemplateExtensions).Assembly;

            int index = 0;            

            foreach(var resName in selfAssembly.GetManifestResourceNames())
            {
                if (resName.EndsWith(".cs"))
                {
                    using (var s = selfAssembly.GetManifestResourceStream(resName))
                    {
                        using (var t = new System.IO.StreamReader(s))
                        {
                            var code = t.ReadToEnd();
                            code = ProcessTemplate(code, this.RootNameSpace, this.NugetPackages);
                            context.AddSource($"CodeSugar.FileProviders{index}.g.cs", code);
                            index++;
                        }
                    }
                }                
            }
        }

        private static string ProcessTemplate(string templateCode, string nameSpace, IReadOnlyDictionary<string, string> nugets)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();

            foreach (var n in nugets)
            {
                if (n.Key.StartsWith("Microsoft.Extensions") || n.Key == "SharpCompress")
                {
                    var declaration = "#define __REFERENCES_" + n.Key.Replace(".", "").ToUpper();
                    sb.AppendLine(declaration);
                }
            }

            sb.AppendLine();

            templateCode = templateCode
                .Replace("$rootnamespace$", nameSpace)
                .Replace("__CODESUGAR_ROOTNAMESPACE__", nameSpace);
            
            sb.AppendLine(templateCode);

            return sb.ToString();
        }
    }
}
