name: Build a preview and release it to Github

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest    
    timeout-minutes: 5
    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4    

    - name: Build
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh "Prv-DATE-TIME"

    - name: Push to Github
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.CodeSugar_PublishToGithub}} --source https://nuget.pkg.github.com/${{github.repository_owner}}

    - name: publish release tag
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.CODESUGAR_EMITRELEASETAG }}
      with:
        title: Preview release
      
