name: Build a preview and release it to Github

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest    
    timeout-minutes: 5
    permissions:
      contents: write # required by softprops/action-gh-release@v2
    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Define Version
      run: |
        PACKAGEVERSION="1.0.0-Prv-DATE-TIME"
        # replace date
        DATE_SHORT=$(date +'%Y%m%d')
        PACKAGEVERSION="${PACKAGEVERSION/DATE/$DATE_SHORT}"
        # replace time
        TIME_SHORT=$(date +'%H%M%S')
        PACKAGEVERSION="${PACKAGEVERSION/TIME/$TIME_SHORT}"
        # report
        echo "package version: $PACKAGEVERSION";
        echo "GHENV_PACKAGEVERSION=$PACKAGEVERSION" >> $GITHUB_ENV
        

    - name: Build
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh $GHENV_PACKAGEVERSION

    # - name: Push to Github
    #   run: dotnet nuget push "*.nupkg" --api-key ${{secrets.CodeSugar_PublishToGithub}} --source https://nuget.pkg.github.com/${{github.repository_owner}}    

    - name: publish release tag
      # https://github.com/elgohr/Github-Release-Action
      # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v2    
      with:
        name: "Prerelease $GHENV_PACKAGEVERSION"
        prerelease: true
        generate_release_notes: true
        make_latest: false
      
