name: Build a preview and release it to NUGET

on: workflow_dispatch
    
jobs:      

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing the tag    
      id-token: write # enable GitHub OIDC token issuance for this job
    
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |            
          8.0.x
          10.0.x

    # ---------------------------------------------  Android SDK

    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'          

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4

    # ---------------------------------------------  Workloads

    - name: Install Workload
      run: dotnet workload install maui-windows android wasm-tools wasi-experimental  # ios and maui-ios are not supported in ubuntu machines https://github.com/dotnet/maui/issues/15929

    # ---------------------------------------------  Builds

    - name: Define Version at GHENV_PACKAGEVERSION
      run: |
        chmod +x ./.github/workflows/FormatSemver.sh
        ./.github/workflows/FormatSemver.sh "1.0.0-Prv-DATE" >> $GITHUB_ENV

    - name: Build Packed Sources
      run: |
        chmod +x ./CodeSugar.Src.Build.sh
        ./CodeSugar.Src.Build.sh $GHENV_PACKAGEVERSION

    - name: Define Version at GHENV_PACKAGEVERSION
      run: |
        chmod +x ./.github/workflows/FormatSemver.sh
        ./.github/workflows/FormatSemver.sh "1.0.0-Prv-DATE-TIME" >> $GITHUB_ENV

    - name: Build Source Generators
      run: |
        chmod +x ./CodeSugar.Gen.Build.sh
        ./CodeSugar.Gen.Build.sh $GHENV_PACKAGEVERSION

    # ------------------------------------------ Push packages

    # Get a short-lived NuGet API key
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER_NAME }}

    - name: NuGet push
      run: dotnet nuget push "*.nupkg" --skip-duplicate --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    # ------------------------------------------ Create tag

    - name: create tag
      uses: ./.github/actions/PushGithubTag
      with:
        tag-name: "${{env.GHENV_PACKAGEVERSION}}"
        message: "new tag for ${{env.GHENV_PACKAGEVERSION}}"
