name: Build a preview and release it to Github

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest    
    timeout-minutes: 5
    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4    

    - name: Build
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh "Prv-DATE-TIME"

    - name: Push to Github
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.CodeSugar_PublishToGithub}} --source https://nuget.pkg.github.com/${{github.repository_owner}}

    - name: Generate Changelog
      run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

    - name: publish release tag
      # https://github.com/elgohr/Github-Release-Action
      # https://github.com/softprops/action-gh-release      
      uses: https://github.com/softprops/action-gh-release      
      with:
        # token: ${{ secrets.CODESUGAR_EMITRELEASETAG }}
        title: Draft release
        draft: true
        prerelease: true
        generate_release_notes: true
        make_latest: false
      
