name: Build a preview and release it to Github

on: workflow_dispatch
    
jobs:

  build_job: #---------------------------------------------------------------------------------------

    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing the tag

    outputs:
      # parameters to pass to tag creation job
      tag-name: "Preview-${{env.GHENV_PACKAGEVERSION}}"
      tag-message: "new tag"
    
    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Define Version at GHENV_PACKAGEVERSION
      run: |
        chmod +x ./.github/workflows/FormatSemver.sh
        ./.github/workflows/FormatSemver.sh "1.0.0-Prv-DATE-TIME" >> $GITHUB_ENV

    - name: Build
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh $GHENV_PACKAGEVERSION

    


    # - name: Push to Github
    #   run: dotnet nuget push "*.nupkg" --api-key ${{secrets.CodeSugar_PublishToGithub}} --source https://nuget.pkg.github.com/${{github.repository_owner}}        


    - name: create tag
      uses: ./.github/actions/PushGithubTag
      with:
        tag-name: "Preview-test-${{env.GHENV_PACKAGEVERSION}}"
        message: "new tag"

  # tag_job: #---------------------------------------------------------------------------------------

  #   needs: build_job    
  #   permissions:
  #     contents: write # required for pushing the tag    
  #   uses: ./.github/workflows/PushGithubTag.yml
  #   with:
  #     tag-name: "${{needs.build_job.outputs.tag-name}}"
  #     message: "${{needs.build_job.outputs.tag-message}}"
     
    # - name: create release
    #   # https://github.com/elgohr/Github-Release-Action
    #   # https://github.com/softprops/action-gh-release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/') # this action requires a release tag
    #   with:
    #     tag_name: "Preview ${{ env.GHENV_PACKAGEVERSION}}"
    #     prerelease: true
    #     generate_release_notes: true
    #     make_latest: false    
      
