name: Build a preview and release it to Github

on: workflow_dispatch
    
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing the tag    
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Define Version at GHENV_PACKAGEVERSION
      run: |
        chmod +x ./.github/workflows/FormatSemver.sh
        ./.github/workflows/FormatSemver.sh "1.0.0-Prv-DATE-TIME" >> $GITHUB_ENV

    - name: Build
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh $GHENV_PACKAGEVERSION

    - name: Push to Github
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.CodeSugar_PublishToGithub}} --source https://nuget.pkg.github.com/${{github.repository_owner}}

    - name: create tag
      uses: ./.github/actions/PushGithubTag
      with:
        tag-name: "${{env.GHENV_PACKAGEVERSION}}"
        message: "new tag for ${{env.GHENV_PACKAGEVERSION}}"
