name: Push a new github tag

on:

  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: 'name of the tag'
        required: true
        default: 'tag'
      message:
        type: string
        description: 'message'
        required: false
        default: 'message'

  workflow_call:
    inputs:
      tag-name:
        type: string
        description: 'name of the tag'
        required: true
        default: 'tag'
      message:
        type: string
        description: 'message'
        required: false
        default: 'message'
    
jobs:
  build_job:

    runs-on: ubuntu-latest    
    timeout-minutes: 1
    permissions:
      contents: write # required for pushing the tag

    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    # https://github.com/orgs/community/discussions/40405
    - run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git tag -a "${{inputs.tag-name}}" -m "${{inputs.message}}"
        git push origin "${{inputs.tag-name}}"

    # # alternative solution:
    # # https://github.com/rickstaa/action-create-tag
    # - name: create tag
    #   uses: rickstaa/action-create-tag@v1
    #   id: "tag_create"
    #   with:
    #     tag: "${{inputs.tag-name}}"
    #     tag_exists_error: true
    #     message: "${{inputs.message}}"