name: Build a preview and release it to Nuget

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VersionSuffix: "preview-${{(date '+%Y%m%d-%H%M')}}"
    timeout-minutes: 5
    steps:
    - name: define version suffix
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
      env:
        VersionSuffix: Preview-${{ steps.date.outputs.date }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --version-suffix $env:VersionSuffix
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
#    - name: Push to NuGet
#      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
