name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:        
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |            
          8.0.x
          10.0.x

    # ---------------------------------------------  Android SDK

    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'          

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4

    # ---------------------------------------------  Workloads

    - name: Install Workload
      run: dotnet workload install maui-windows android wasm-tools wasi-experimental  # ios and maui-ios are not supported in ubuntu machines https://github.com/dotnet/maui/issues/15929

    # ---------------------------------------------  Builds
    
    - name: Build Source Generators
      run: |
        chmod +x ./CodeSugar.Build.sh
        ./CodeSugar.Build.sh "1.0.0"
